# Site settings
title: Rock Robotics
email: tiago.cajahyba@fieb.org.br
description: > # this means to ignore newlines until "baseurl:"
  Um site qualquer
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: rock-robotics
github_username:  rock-robotics

# Build settings
markdown: kramdown

# Outputting
permalink: none
